version: '3.8'
services:
  php-apache:
    build: 
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - type: bind
        source: ./apache2/apache2.conf
        target: /etc/apache2/apache2.conf
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - 3307:3306
    env_file:
      - .env
    volumes:
      - type: volume
        source: php-contact-vol
        target: /var/lib/mysql
    
volumes:
    php-contact-vol: 